"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
require("./babel");
require("./comments");
require("./es6tests");
require("./identity");
require("./jsx");
require("./lines");
require("./mapping");
require("./parens");
require("./parser");
require("./patcher");
require("./perf");
require("./printer");
require("./syntax");
require("./flow");
require("./typescript");
require("./visit");
